#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Aliases
alias dmesg="dmesg --human --color=always"
alias rm='echo "Use \\\rm or trash (trash-cli)."; false'

# Notify on long-running commands
# install undistract-me
source /usr/share/undistract-me/long-running.bash
notify_when_long_running_commands_finish_install
